version: '3.8'

services:
  restapp-backend:
    build: .
    container_name: restapp-backend
    command: ["./build/app/RestApp", "0.0.0.0", "8080"]
    ports:
      - "8080:8080"
    links:
      - "postgres-server:database"
    depends_on:
      - postgres-server

  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_DB: restapp
      POSTGRES_USER: restapp
      POSTGRES_PASSWORD: test123
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"